###
# @name Sale
# Variables de entorno para las pruebas de Sale
@token = ey... (Pega aquí tu token JWT)
@baseUrl = http://localhost:4000

### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los sales (SIN token)
GET {{baseUrl}}/api/sales/public

### Obtener Sale por ID (SIN token)
GET {{baseUrl}}/api/sales/public/1

### Crear un nuevo Sale (SIN token)
POST {{baseUrl}}/api/sales/public
Content-Type: application/json

{
    "sale_date": "2025-11-16T23:32:01.000Z",
    "subtotal": "valor de ejemplo",
    "tax": "valor de ejemplo",
    "discounts": "valor de ejemplo",
    "total": "valor de ejemplo",
    "status": "ACTIVE"
}

### Actualizar un Sale (SIN token)
PATCH {{baseUrl}}/api/sales/public/1
Content-Type: application/json

{
  "name": "Nombre Actualizado"
}

### Eliminar un Sale físicamente (SIN token)
DELETE {{baseUrl}}/api/sales/public/1

### Eliminar un Sale lógicamente (SIN token)
DELETE {{baseUrl}}/api/sales/public/2/logic

### ================== RUTAS CON AUTENTICACIÓN ==================

### Obtener todos los sales (CON token)
GET {{baseUrl}}/api/sales
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener un Sale por ID (CON token)
GET {{baseUrl}}/api/sales/1
Content-Type: application/json
Authorization: Bearer {{token}}

### Crear un nuevo Sale (CON token)
POST {{baseUrl}}/api/sales
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "sale_date": "2025-11-16T23:32:01.000Z",
    "subtotal": "valor de ejemplo",
    "tax": "valor de ejemplo",
    "discounts": "valor de ejemplo",
    "total": "valor de ejemplo",
    "status": "ACTIVE"
}

### Actualizar un Sale existente (CON token)
PATCH {{baseUrl}}/api/sales/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Nombre Actualizado"
}

### Eliminar un Sale físicamente (CON token)
DELETE {{baseUrl}}/api/sales/1
Authorization: Bearer {{token}}

### Borrado lógico de un Sale (CON token)
DELETE {{baseUrl}}/api/sales/1/logic
Content-Type: application/json
Authorization: Bearer {{token}}
