### auth.http

@baseUrl = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzYxMTU0OTc1LCJleHAiOjE3NjExNTU1NzV9.8pY_4eGzYPK7JnX4HHtBZoVnHWS9DhaPB0MG4nZa1MI

## ================== RUTAS SIN AUTENTICACIÓN ==================

### Registrar un nuevo usuario
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "username": "yoner",
  "email": "yoner@gmail.com",
  "password": "yoner",
  "is_active": "ACTIVE",
  "avatar": "avatar.jpg"
}

### Iniciar sesión
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "email": "yoner@gmail.com",
  "password": "yoner"
}


### Obtener todos los usuarios
GET {{baseUrl}}/api/users

### ================== RUTAS CON AUTENTICACIÓN ==================