###
# @name Hotel
# Variables de entorno para las pruebas de Hotel
@token = ey... (Pega aquí tu token JWT)
@baseUrl = http://localhost:4000

### ================== RUTAS SIN AUTENTICACIÓN ==================

### Obtener todos los hotels (SIN token)
GET {{baseUrl}}/api/hotels/public

### Obtener Hotel por ID (SIN token)
GET {{baseUrl}}/api/hotels/public/1

### Crear un nuevo Hotel (SIN token)
POST {{baseUrl}}/api/hotels/public
Content-Type: application/json

{
    "name": "John Doe",
    "address": "123 Main St",
    "city": "valor de ejemplo",
    "country": "valor de ejemplo",
    "phone": "3001234567",
    "stars": "valor de ejemplo",
    "status": "ACTIVE"
}

### Actualizar un Hotel (SIN token)
PATCH {{baseUrl}}/api/hotels/public/1
Content-Type: application/json

{
  "name": "Nombre Actualizado"
}

### Eliminar un Hotel físicamente (SIN token)
DELETE {{baseUrl}}/api/hotels/public/1

### Eliminar un Hotel lógicamente (SIN token)
DELETE {{baseUrl}}/api/hotels/public/2/logic

### ================== RUTAS CON AUTENTICACIÓN ==================

### Obtener todos los hotels (CON token)
GET {{baseUrl}}/api/hotels
Content-Type: application/json
Authorization: Bearer {{token}}

### Obtener un Hotel por ID (CON token)
GET {{baseUrl}}/api/hotels/1
Content-Type: application/json
Authorization: Bearer {{token}}

### Crear un nuevo Hotel (CON token)
POST {{baseUrl}}/api/hotels
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "John Doe",
    "address": "123 Main St",
    "city": "valor de ejemplo",
    "country": "valor de ejemplo",
    "phone": "3001234567",
    "stars": "valor de ejemplo",
    "status": "ACTIVE"
}

### Actualizar un Hotel existente (CON token)
PATCH {{baseUrl}}/api/hotels/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Nombre Actualizado"
}

### Eliminar un Hotel físicamente (CON token)
DELETE {{baseUrl}}/api/hotels/1
Authorization: Bearer {{token}}

### Borrado lógico de un Hotel (CON token)
DELETE {{baseUrl}}/api/hotels/1/logic
Content-Type: application/json
Authorization: Bearer {{token}}
